const cases=[
{id:1,name:"O Arquivo Fantasma",difficulty:"Iniciante",intro:"A Helix Systems sofreu uma invasão silenciosa. Um arquivo confidencial desapareceu e uma conta desativada, ORPHEUS-07, voltou a assinar pacotes.",details:"Você encontra registros de acesso no nó HXS-04. A mensagem deixada pelo invasor diz: “O arquivo nunca foi excluído. Ele aprendeu a se esconder.” Descubra a palavra-chave e identifique a rota usada.",question:"Decodifique 3-1-19-5 usando A1Z26.",answer:["case"],evidence:["Registro de acesso no nó HXS-04","Mensagem decodificada: CASE","Assinatura digital de ORPHEUS-07"],suspects:[["Lívia Moura","Analista de segurança; álibi não verificado."],["Rafael Costa","Administrador de rede com acesso elevado."],["ORPHEUS-07","Identidade digital desativada há três anos."]],ending:"A palavra CASE revela que o arquivo está em um diretório legado. A assinatura aponta para ORPHEUS-07, mas ainda não prova quem controlou a conta."},
{id:2,name:"O Cofre de Vidro",difficulty:"Iniciante",intro:"Uma startup de pagamentos perdeu o acesso ao cofre de chaves. O sistema não foi invadido: alguém convenceu o suporte a liberar uma sessão temporária.",details:"Três atendentes receberam mensagens semelhantes. Os horários formam uma sequência e o cofre só abre quando você identifica o padrão.",question:"Complete a sequência: 2, 4, 8, 16, ?",answer:["32","trinta e dois"],evidence:["Chamados de suporte sincronizados","Sequência duplicada de autenticação","Token temporário liberado"],suspects:[["Nina Alves","Supervisora do suporte."],["Caio Nunes","Terceirizado com acesso a chamados."],["Conta BOT-22","Automação usada para triagem."]],ending:"O padrão revela a janela de autenticação. O golpe explorou procedimentos humanos, não uma falha criptográfica."},
{id:3,name:"A Cidade Sem Sinal",difficulty:"Intermediário",intro:"Uma cidade inteligente perde os sinais de trânsito durante nove minutos. Câmeras mostram apenas imagens congeladas e os controladores continuam respondendo a comandos.",details:"Os pacotes de controle carregam uma mensagem fragmentada. A ordem dos termos é a chave para reconstruir o comando.",question:"Organize as palavras para formar a instrução: SINAL / RESTAURE / AGORA.",answer:["restaure sinal agora","restaure o sinal agora"],evidence:["Pacotes de controle fragmentados","Janela de nove minutos","Comando reconstruído de restauração"],suspects:[["Mara Reis","Engenheira de mobilidade."],["Davi Torres","Prestador de manutenção."],["Nó CENTRAL-9","Controlador comprometido."]],ending:"A instrução reconstruída restaura os sinais, mas mostra que o invasor testava a infraestrutura para um ataque maior."},
{id:4,name:"O Perfil Duplicado",difficulty:"Intermediário",intro:"Uma jornalista recebe ameaças de um perfil que copia sua identidade digital. O perfil falso publica informações verdadeiras, mas em horários impossíveis.",details:"Você compara metadados, fusos horários e horários de publicação. A diferença constante indica que o autor usa um relógio deslocado.",question:"Se o horário real é 18:00 e o registro mostra 21:00, qual é o deslocamento em horas?",answer:["3","+3","mais 3"],evidence:["Metadados de publicações","Deslocamento de fuso de três horas","Padrão de cópia de identidade"],suspects:[["Helena Prado","Editora que tinha acesso ao calendário."],["Otávio Lima","Especialista em automação de redes sociais."],["Perfil MIRROR","Identidade falsa com atividade programada."]],ending:"O deslocamento temporal conecta as publicações a uma rotina automatizada. O perfil falso foi programado, não operado em tempo real."},
{id:5,name:"O Código da Estação",difficulty:"Avançado",intro:"Uma estação de pesquisa recebe uma transmissão de emergência. A mensagem usa símbolos em vez de letras e repete três marcas em intervalos regulares.",details:"O padrão é um código simples de substituição. Cada símbolo representa a letra seguinte no alfabeto.",question:"Se A vira B, B vira C e C vira D, qual é a transformação de Z?",answer:["a"],evidence:["Transmissão de emergência","Tabela de substituição deslocada","Mensagem convertida para texto legível"],suspects:[["Ícaro Vaz","Operador da estação."],["Sofia Brandão","Pesquisadora responsável pelo rádio."],["Canal DELTA","Frequência não autorizada."]],ending:"A transformação circular revela que a transmissão foi alterada por uma cifra de deslocamento. A origem veio de um canal não autorizado."},
{id:6,name:"O Último Backup",difficulty:"Avançado",intro:"Um hospital perde o último backup de seus sistemas administrativos. Há três cópias, mas somente uma mantém a cadeia de integridade.",details:"Cada cópia possui um hash simplificado. O backup confiável é aquele cujo valor não foi alterado desde a última auditoria.",question:"Qual cópia é confiável? A=101, B=101, C=110. A auditoria registrou 101.",answer:["a","b","cópia a","copia a","cópia b","copia b"],evidence:["Três cópias de backup","Registro de auditoria com valor 101","Cadeia de integridade preservada"],suspects:[["Paula Siqueira","Administradora do hospital."],["Bruno Farias","Técnico de infraestrutura."],["Backup C","Cópia com valor divergente."]],ending:"A auditoria aponta que as cópias A e B compartilham o mesmo valor. Você preserva ambas para validação, evitando uma restauração precipitada."},
{id:7,name:"Arquivos da Sombra",difficulty:"Final",intro:"As pistas dos seis casos apontam para uma rede clandestina chamada SOMBRA. Ela não rouba dados: testa sistemas para mapear quem reage e como reage.",details:"Você deve escolher entre expor a rede imediatamente ou preservar a operação para capturar o núcleo. A decisão define o encerramento da campanha.",question:"Digite EXPOR para divulgar tudo ou PRESERVAR para montar uma captura controlada.",answer:["expor","preservar"],evidence:["Conexão entre os seis casos","Nome da rede SOMBRA","Mapa de infraestrutura clandestina"],suspects:[["A Curadora","Coordenadora desconhecida da rede SOMBRA."],["Agente Zero","Operador que deixou pistas nos casos anteriores."],["SOMBRA","Rede de testes e manipulação de sistemas."]],ending:"A rede SOMBRA é real e usa incidentes pequenos para estudar respostas de segurança."}
];
let state=JSON.parse(localStorage.getItem("cd_campaign")||'{"current":1,"solved":[],"evidence":[],"xp":0,"level":1,"decisions":{}}');
let active=null;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("cd_campaign",JSON.stringify(state))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function tab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.tab===id))}
function screen(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")}
function stats(){ $("level").textContent="Nível "+state.level;$("xp").textContent=state.xp+"/100";$("xpbar").style.width=state.xp+"%";$("ecount").textContent=state.evidence.length}
function xp(n){state.xp+=n;while(state.xp>=100){state.xp-=100;state.level++;toast("Novo nível desbloqueado!")}save();stats()}
function renderCases(){$("case-list").innerHTML=cases.map(c=>{let done=state.solved.includes(c.id);let locked=c.id>1&&!state.solved.includes(c.id-1);return `<article class="card ${locked?'locked':''}"><div class="smalltag">CASO #${String(c.id).padStart(3,"0")} • ${c.difficulty}</div><h4>${c.name}</h4><p>${locked?"Bloqueado: conclua o caso anterior.":c.intro}</p><button ${locked?'disabled':''} data-case="${c.id}">${done?"Revisar caso":"Investigar"}</button></article>`}).join("")}
function loadCase(id){active=cases.find(c=>c.id===id);state.current=id;$("chapter").textContent="CASO #"+String(id).padStart(3,"0")+" / 7";$("title").textContent=active.name;$("difficulty").textContent=active.difficulty;$("story").innerHTML=`<p>${active.intro}</p><p>${active.details}</p>`;$("puzzle").innerHTML=`<h4>Enigma do caso</h4><p>${active.question}</p><label>Resposta</label><input id="answer" placeholder="Digite sua resposta"><button class="primary" id="check">Validar resposta</button><p id="feedback"></p>`;$("advance").disabled=!state.solved.includes(id);$("advance").textContent=id===7?"Ver epílogo →":"Concluir caso →";$("check").onclick=check;renderEvidence();renderSuspects();renderEnding();tab("briefing")}
function check(){let val=$("answer").value.trim().toLowerCase().replace(/[áàãâ]/g,"a").replace(/[éê]/g,"e").replace(/[í]/g,"i").replace(/[óôõ]/g,"o").replace(/[ú]/g,"u");let ok=active.answer.includes(val);if(active.id===7)ok=active.answer.includes(val);if(ok){$("feedback").textContent="✓ Resposta aceita. Evidências desbloqueadas.";if(!state.solved.includes(active.id)){state.solved.push(active.id);active.evidence.forEach(e=>{if(!state.evidence.includes("C"+active.id+":"+e))state.evidence.push("C"+active.id+":"+e)});xp(35);toast("Caso resolvido!");save();renderCases();renderEvidence()}$("advance").disabled=false}else $("feedback").textContent="✕ Resposta incorreta. Analise novamente as pistas."}
function renderEvidence(){$("evidence-list").innerHTML=state.evidence.length?state.evidence.map(e=>`<article class="card"><div class="evidence-icon">◈</div><h4>${e.split(":").slice(1).join(":")}</h4><p>Evidência registrada durante a investigação.</p></article>`).join(""):`<div class="panel">Nenhuma evidência coletada ainda.</div>`}
function renderSuspects(){if(!active){$("suspect-list").innerHTML="";return}$("suspect-list").innerHTML=active.suspects.map(s=>`<article class="card"><div class="smalltag">PERFIL</div><h4>${s[0]}</h4><p>${s[1]}</p></article>`).join("")}
function renderEnding(){if(!active){$("ending-content").textContent="Selecione um caso.";return}let solved=state.solved.includes(active.id);let decision=state.decisions[active.id];$("ending-content").className="panel "+(solved?"final-good":"");$("ending-content").innerHTML=solved?`<h4>${active.name}</h4><p>${active.ending}</p><p><b>Status:</b> Caso concluído.</p>${decision?`<p><b>Decisão:</b> ${decision}</p>`:""}`:"<p>Conclua o enigma para liberar o relatório final."}
function terminalPrint(t,cl=""){let p=document.createElement("p");p.textContent=t;if(cl)p.style.color=cl;$("output").appendChild(p);$("output").scrollTop=$("output").scrollHeight}
function command(raw){let c=raw.trim().toLowerCase();if(!c)return;terminalPrint("agent@forge:$ "+raw);if(c==="clear"){$("output").innerHTML="";return}if(c==="help"){["help — comandos","case — caso atual","clues — pistas do caso","suspects — suspeitos","status — progresso","solve RESPOSTA — validar enigma","clear — limpar terminal"].forEach(x=>terminalPrint(x));return}if(c==="case"){terminalPrint(active?active.name:"Nenhum caso selecionado");return}if(c==="clues"){if(active)active.evidence.forEach(x=>terminalPrint(x));return}if(c==="suspects"){if(active)active.suspects.forEach(x=>terminalPrint(x[0]+" — "+x[1]));return}if(c==="status"){terminalPrint("Casos concluídos: "+state.solved.length+"/7");terminalPrint("XP: "+state.xp+"/100");return}if(c.startsWith("solve ")){if(!active){terminalPrint("Selecione um caso primeiro.");return}$("answer").value=raw.slice(6);check();return}terminalPrint("Comando desconhecido. Digite help.")}
$("termform").addEventListener("submit",e=>{e.preventDefault();command($("cmd").value);$("cmd").value=""});
document.addEventListener("click",e=>{let act=e.target.dataset.act;if(act==="start"){state.current=1;save();screen("game");renderCases();loadCase(1);stats()}if(act==="continue"){screen("game");renderCases();loadCase(state.current||1);stats()}if(act==="how")screen("how");if(act==="menu")screen("menu");if(act==="wipe"&&confirm("Apagar toda a campanha?")){localStorage.removeItem("cd_campaign");location.reload()}if(e.target.dataset.case){loadCase(Number(e.target.dataset.case))}if(e.target.dataset.tab)tab(e.target.dataset.tab);if(act==="advance"){if(active.id<7){loadCase(active.id+1);toast("Próximo caso desbloqueado.")}else{state.decisions[7]="Campanha concluída";save();renderEnding();tab("ending");toast("Campanha finalizada!")}}});
stats();renderCases();